// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oaawbawzoewutrbtorle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hYXdiYXd6b2V3dXRyYnRvcmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwODA5NjksImV4cCI6MjA2MDY1Njk2OX0.Da_GN6lxpmHO49IoFzkCWI5IzkKgP_5GX9pnzntLlpw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);